### ISSUE TITLE
Not updated on flathub

### ISSUE THREAD

**Issue by aadilayub** [zen-browser/flatpak#8] opened 2024-09-04 05:28 UTC
The latest version on flathub is two weeks old, whereas the latest release in the repo is 8 hours ago.

**Comment by LeMoonStar** [comment] 2024-09-06 19:34
The cause is a wrong ordering of the Releases section in the metadata XML-File - This is only happening since an automatic workflow took over the job of adding new releases.

I submitted a temporary fix with #13 - But the workflow itself has to be fixed as well.

**Comment by mauro-balades** [comment] 2024-10-04 13:10
Should be fixed now, thanks!

**Closed by mauro-balades** 2024-10-04 13:10 UTC
